[package]
name = "bridge"
version = "0.1.0"
description = "Solana source-chain bridge program (lock SPL for EVM mint)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "bridge"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[lints]
workspace = true

[dependencies]
anchor-lang = { version = "1.1.2", features = ["init-if-needed"] }
anchor-spl = "1.1.2"
solana-keccak-hasher = { version = "3", features = ["sha3"] }
solana-secp256k1-recover = "3"

[dev-dependencies]
hex = "0.4"
